// Transcribed from data/curcumin_confidence_level_mock.csv — mock "Interaction
// Degree (%)" (confidence level in the interaction estimate) for all 104 real
// drugs in the seeded dataset.
const CONFIDENCE_BY_DRUG = {
  '5-fluorouracil': 2,
  'abemaciclib': 72,
  'abiraterone': 16,
  'acalabrutinib': 12,
  'adc - dm1 / dm4 payload': 93,
  'adc - dxd / mmae payload': 10,
  'adc - sn-38 payload': 52,
  'afatinib': 47,
  'alectinib': 12,
  'anastrozole': 52,
  'anti-ctla4': 99,
  'anti-pd1': 10,
  'anti-pdl1': 2,
  'apalutamide': 59,
  'axitinib': 47,
  'belinostat': 63,
  'bevacizumab': 4,
  'binimetinib': 82,
  'bites': 7,
  'bleomycin': 79,
  'bosutinib': 54,
  'brigatinib': 59,
  'busulfan': 64,
  'cabozantinib': 83,
  'capecitabine': 88,
  'carboplatin': 12,
  'ceritinib': 76,
  'cetuximab': 53,
  'cisplatin': 63,
  'cobimetinib': 92,
  'crizotinib': 19,
  'cyclophosphamide (iv)': 82,
  'cyclophosphamide (oral)': 10,
  'cytarabine': 1,
  'dacarbazine': 50,
  'darolutamide': 28,
  'dasatinib': 45,
  'docetaxel': 88,
  'doxorubicin': 48,
  'encorafenib': 74,
  'entrectinib': 94,
  'enzalutamide': 92,
  'erlotinib': 68,
  'etoposide (iv)': 1,
  'etoposide (oral)': 27,
  'everolimus': 63,
  'exemestane': 81,
  'gefitinib': 20,
  'gemcitabine': 87,
  'hydroxyurea': 81,
  'ibrutinib': 43,
  'ifosfamide': 72,
  'imatinib': 55,
  'irinotecan': 42,
  'ivosidenib': 45,
  'lapatinib': 5,
  'larotrectinib': 65,
  'lenvatinib': 20,
  'letrozole': 97,
  'lorlatinib': 75,
  'melphalan': 73,
  'methotrexate': 2,
  'neratinib': 64,
  'nilotinib': 44,
  'niraparib': 70,
  'olaparib': 3,
  'osimertinib': 61,
  'oxaliplatin': 66,
  'paclitaxel': 55,
  'palbociclib': 4,
  'panitumumab': 10,
  'pazopanib': 2,
  'pemetrexed': 70,
  'pertuzumab': 11,
  'pexidartinib': 100,
  'ponatinib': 73,
  'procarbazine': 57,
  'ramucirumab': 72,
  'regorafenib': 21,
  'ribociclib': 52,
  'rituximab': 90,
  'rucaparib': 80,
  'selpercatinib': 78,
  'sonidegib': 73,
  'sorafenib': 2,
  'sunitinib': 38,
  'talazoparib': 52,
  'tamoxifen': 1,
  'tas-102': 63,
  'temozolomide': 34,
  'tivozanib': 33,
  'topotecan (iv)': 30,
  'topotecan (oral)': 74,
  'trametinib': 88,
  'trastuzumab': 59,
  'tucatinib': 92,
  'vandetanib': 5,
  'vemurafenib': 91,
  'venetoclax': 58,
  'vinblastine': 44,
  'vincristine': 9,
  'vinorelbine (iv)': 35,
  'vinorelbine (oral)': 56,
  'vismodegib': 19,
};

export function interactionConfidence(interaction) {
  if (!interaction) return 0;
  const key = interaction.drug_name.trim().toLowerCase();
  return CONFIDENCE_BY_DRUG[key] ?? 0;
}
