// Transcribed from data/curcumin_degree_of_interaction_mock.csv — mock 1-5
// "degree of interaction" scale (how much curcumin is predicted to affect the
// drug's pharmacokinetics) for all 104 real drugs in the seeded dataset.
const DEGREE_BY_DRUG = {
  '5-fluorouracil': 2,
  'abemaciclib': 4,
  'abiraterone': 5,
  'acalabrutinib': 2,
  'adc - dm1 / dm4 payload': 3,
  'adc - dxd / mmae payload': 3,
  'adc - sn-38 payload': 2,
  'afatinib': 1,
  'alectinib': 2,
  'anastrozole': 5,
  'anti-ctla4': 1,
  'anti-pd1': 5,
  'anti-pdl1': 4,
  'apalutamide': 5,
  'axitinib': 4,
  'belinostat': 3,
  'bevacizumab': 2,
  'binimetinib': 4,
  'bites': 5,
  'bleomycin': 2,
  'bosutinib': 3,
  'brigatinib': 5,
  'busulfan': 1,
  'cabozantinib': 4,
  'capecitabine': 4,
  'carboplatin': 2,
  'ceritinib': 1,
  'cetuximab': 5,
  'cisplatin': 5,
  'cobimetinib': 2,
  'crizotinib': 4,
  'cyclophosphamide (iv)': 4,
  'cyclophosphamide (oral)': 4,
  'cytarabine': 2,
  'dacarbazine': 5,
  'darolutamide': 4,
  'dasatinib': 3,
  'docetaxel': 2,
  'doxorubicin': 2,
  'encorafenib': 2,
  'entrectinib': 1,
  'enzalutamide': 3,
  'erlotinib': 2,
  'etoposide (iv)': 3,
  'etoposide (oral)': 5,
  'everolimus': 4,
  'exemestane': 5,
  'gefitinib': 2,
  'gemcitabine': 5,
  'hydroxyurea': 2,
  'ibrutinib': 4,
  'ifosfamide': 1,
  'imatinib': 4,
  'irinotecan': 4,
  'ivosidenib': 5,
  'lapatinib': 5,
  'larotrectinib': 4,
  'lenvatinib': 4,
  'letrozole': 3,
  'lorlatinib': 3,
  'melphalan': 5,
  'methotrexate': 3,
  'neratinib': 5,
  'nilotinib': 3,
  'niraparib': 5,
  'olaparib': 2,
  'osimertinib': 1,
  'oxaliplatin': 1,
  'paclitaxel': 2,
  'palbociclib': 2,
  'panitumumab': 1,
  'pazopanib': 5,
  'pemetrexed': 2,
  'pertuzumab': 5,
  'pexidartinib': 1,
  'ponatinib': 3,
  'procarbazine': 4,
  'ramucirumab': 1,
  'regorafenib': 5,
  'ribociclib': 1,
  'rituximab': 5,
  'rucaparib': 3,
  'selpercatinib': 3,
  'sonidegib': 1,
  'sorafenib': 5,
  'sunitinib': 5,
  'talazoparib': 5,
  'tamoxifen': 5,
  'tas-102': 3,
  'temozolomide': 4,
  'tivozanib': 3,
  'topotecan (iv)': 2,
  'topotecan (oral)': 5,
  'trametinib': 3,
  'trastuzumab': 5,
  'tucatinib': 1,
  'vandetanib': 1,
  'vemurafenib': 2,
  'venetoclax': 1,
  'vinblastine': 4,
  'vincristine': 1,
  'vinorelbine (iv)': 1,
  'vinorelbine (oral)': 4,
  'vismodegib': 2,
};

export function mockInteractionDegree(interaction) {
  if (!interaction) return 0;
  const key = interaction.drug_name.trim().toLowerCase();
  return DEGREE_BY_DRUG[key] ?? 0;
}
